name: Documentation Branch Workflow

on:
  push:
    branches:
      - docs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Add your docs branch workflow steps here
