name: Enforce Branch Naming

on:
  push:
    branches:
      - '*'

jobs:
  enforce-branch-naming:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check Branch Naming
        run: |
          BRANCH_NAME=$(git branch --show-current)

          # Define the allowed branch patterns
          ALLOWED_PATTERNS="^(hotfix-.*|release-.*|bugfix-.*|feature-.*)$"

          # Check if the branch name matches the allowed patterns
          if [[ ! "$BRANCH_NAME" =~ $ALLOWED_PATTERNS ]]; then
            echo "Error: Branch name '$BRANCH_NAME' does not match the allowed patterns."
            exit 1
          fi
